#ifndef	__LCD_ZK_H__
#define	__LCD_ZK_H__

//字号因子
#define	_8x16		1//	0
#define	_16x16		2//	1
#define	_16x32		4//	2
#define	_32x32		8//	3
//0123456789%.AGKMP本标厂场程出到点电定丢动堵度阀反否复高关号恢基级间精开码密起入上设失时是手输停位温下现限校信用远正值制置转准子自作
//*
//基础编号(名称)	//(选字序号=基础编号 * 字号因子 , 另外，数字字母与汉字调用不同程序)
#define	_0		0//	0
#define	_1		1//	1
#define	_2		2//	2
#define	_3		3//	3
#define	_4		4//	4
#define	_5		5//	5
#define	_6		6//	6
#define	_7		7//	7
#define	_8		8//	8
#define	_9		9//	9
#define	_Per	10//	%
#define	_Point	11//	.
#define	_A		12//	A
#define	_G		13//	G
#define	_K		14//	K
#define	_M		15//	M
#define	_P		16//	P
#define	_Ben	17//	本
#define	_Biao	19//	标
#define	_Chang	21//	厂
#define	_Chang1	23//	场
#define	_Cheng	25//	程
#define	_Chu	27//	出
#define	_Chu1	29//	出
#define	_Dao	31//	到
#define	_Diao	33//	点
#define	_Dian	35//	电
#define	_Ding	37//	定
#define	_Diu	39//	丢
#define	_Dong	41//	动
#define	_Du		43//	堵
#define	_Du1	45//	度
#define	_Fa		47//	阀
#define	_Fan	49//	反
#define	_Fou	51//	否
#define	_Fou1	53//	否
#define	_Fu		55//	复
#define	_Gao	57//	高
#define	_Guan	59//	关
#define	_Hao	61//	号
#define	_Hui	63//	恢
#define	_Ji		65//	基
#define	_Ji1	67//	级
#define	_Jian	69//	间
#define	_Jing	71//	精
#define	_Kai	73//	开
#define	_Ma		75//	码
#define	_Mi		77//	密
#define	_Qi		79//	起
#define	_Ru		81//	入
#define	_Shang	83//	上
#define	_She	85//	设
#define	_Shi	87//	失
#define	_Shi1	89//	时
#define	_Shi2	91//	是
#define	_Shi3	93//	是
#define	_Shou	95//	手
#define	_Shu	97//	输
#define	_Ting	99//	停
#define	_Wei	101//	位
#define	_Wen	103//	温
#define	_Xia	105//	下
#define	_Xian	107//	现
#define	_Xian1	109//	限
#define	_Xiao	111//	校
#define	_Xin	113//	信
#define	_Yong	115//	用
#define	_Yuan	117//	远
#define	_Zheng	119//	正
#define	_Zhi	121//	值
#define	_Zhi1	123//	制
#define	_Zhi2	125//	置
#define	_Zhuan	127//	转
#define	_Zhun	129//	准
#define	_Zi		131//	子
#define	_Zi1	133//	自
#define	_Zuo	135//	作
//*/
/*
#define	_0		0
#define	_1		1
#define	_2		2
#define	_3		3
#define	_4		4
#define	_5		5
#define	_6		6
#define	_7		7
#define	_8		8
#define	_9		9
#define	_Per	10
#define	_Point	11
#define	_A		12
#define	_G		13
#define	_K		14
#define	_M		15
#define	_P		16
#define	_Ben	17
#define	_Biao	19
#define	_Chang	21
#define	_Chang1	23
#define	_Cheng	25
#define	_Chu	27
#define	_Chu1	29
#define	_Dao	31
#define	_Diao	33
#define	_Dian	35
#define	_Ding	37
#define	_Diu	39
#define	_Dong	41
#define	_Du		43
#define	_Du1	45
#define	_Fa		47
#define	_Fan	49
#define	_Fou	51
#define	_Fou1	53
#define	_Fu		55
#define	_Gao	57
#define	_Guan	59
#define	_Hao	61
#define	_Hui	63
#define	_Ji		65
#define	_Ji1	67
#define	_Jian	69
#define	_Jing	71
#define	_Kai	73
#define	_Ma		75
#define	_Mi		77
#define	_Qi		79
#define	_Ru		81
#define	_Shang	83
#define	_She	85
#define	_Shi	87
#define	_Shi1	89
#define	_Shi2	91
#define	_Shi3	93
#define	_Shou	95
#define	_Shu	97
#define	_Ting	99
#define	_Wei	101
#define	_Wen	103
#define	_Xia	105
#define	_Xian	107
#define	_Xian1	109
#define	_Xiao	111
#define	_Xin	113
#define	_Yong	115
#define	_Yuan	117
#define	_Zheng	119
#define	_Zhi	121
#define	_Zhi1	123
#define	_Zhi2	125
#define	_Zhuan	127
#define	_Zhun	129
#define	_Zi		131
#define	_Zi1	133
#define	_Zuo	135
//*/

extern const u16 ZK_8x16[];
extern const u16 ZK_16x16[];
extern const u16 ZK_16x32[];
extern const u16 ZK_32x32[];
extern const u16 ZK_8_16x16B[];
extern const u16 ZK_8_16x32B[];
extern const u16 ZK_16_32x32B[];




#endif

